=== vicious2/hoctap/C21A.TH/XML/Bai_Tap/MinhHoa/BT1_Chuong02/BT1_Chuong02/TienDien.dtd
<!--Dac ta cau truc cac the-->
<!ELEMENT CACHOADON (HDTIENDIEN+)>
<!ELEMENT HDTIENDIEN (KHACHHANG+)>
<!ELEMENT KHACHHANG (HOTEN,DIACHI,SODT?,CHITIET)>
<!ELEMENT HOTEN (#PCDATA)>
<!ELEMENT DIACHI (#PCDATA)>
<!ELEMENT SODT (#PCDATA)>
<!ELEMENT CHITIET (CHISOMOI,CHISOCU,HESO,DONGIA)>
<!ELEMENT CHISOMOI (#PCDATA)>
<!ELEMENT CHISOCU (#PCDATA)>
<!ELEMENT HESO (#PCDATA)>
<!ELEMENT DONGIA (#PCDATA)>
<!--Dac ta cau truc cac thuoc tinh cua the-->
<!ATTLIST HDTIENDIEN
    Thang CDATA #REQUIRED
    TuNgay CDATA #REQUIRED
    DenNgay CDATA #REQUIRED
    CongTy CDATA #FIXED "Công ty điện lực TP.HCM"
>
<!ATTLIST HOTEN
    GT (Nam|Nữ) #REQUIRED
  >

=== vicious2/hoctap/C21A.TH/XML/Bai_Tap/MinhHoa/BT1_Chuong02/BT1_Chuong02/TienDien.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE CACHOADON SYSTEM "TienDien.dtd">
<CACHOADON>
  <HDTIENDIEN  Thang="01" TuNgay="01/01/2018" DenNgay="31/01/2018" CongTy="Công ty điện lực TP.HCM"  >
    <KHACHHANG>
      <HOTEN GT="Nam">Hoàng Anh</HOTEN>
      <DIACHI>342 Hoàng Văn Thụ Q.PN</DIACHI>
      <CHITIET>
        <CHISOMOI>560</CHISOMOI>
        <CHISOCU>500</CHISOCU>
        <HESO>1</HESO>
        <DONGIA>650</DONGIA>
      </CHITIET>      
    </KHACHHANG>
    <KHACHHANG>
      <HOTEN GT="Nữ">Trần Thị Mai</HOTEN>
      <DIACHI>132 Quang Trung Q.Gò Vấp</DIACHI>
      <SODT>0908256400</SODT>
      <CHITIET>
        <CHISOMOI>760</CHISOMOI>
        <CHISOCU>560</CHISOCU>
        <HESO>2</HESO>
        <DONGIA>1200</DONGIA>
      </CHITIET>
    </KHACHHANG>
  </HDTIENDIEN> 
</CACHOADON>
